#pragma once

#define EMBER_MOUSE_BUTTON_1         0
#define EMBER_MOUSE_BUTTON_2         1
#define EMBER_MOUSE_BUTTON_3         2
#define EMBER_MOUSE_BUTTON_4         3
#define EMBER_MOUSE_BUTTON_5         4
#define EMBER_MOUSE_BUTTON_6         5
#define EMBER_MOUSE_BUTTON_7         6
#define EMBER_MOUSE_BUTTON_8         7
#define EMBER_MOUSE_BUTTON_LEFT      EM_MOUSE_BUTTON_1
#define EMBER_MOUSE_BUTTON_RIGHT     EM_MOUSE_BUTTON_2
#define EMBER_MOUSE_BUTTON_MIDDLE    EM_MOUSE_BUTTON_3